[project]
name = "wordbook-cv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.28.0,<1.29.0",
    "opencv-python>=4.9.0",
    "pillow>=10.0.0",
    "numpy>=1.26.0",
    "streamlit-drawable-canvas>=0.9.0",
    "setuptools",
    "ultralytics>=8.4.9",
    "pytesseract>=0.3.10",
    "scikit-learn>=1.8.0",
    "doclayout-yolo>=0.0.4",
    "huggingface-hub>=1.5.0",
]
